modLoader="javafml"
loaderVersion="[41,)"
license="MIT (Code), All Rights Reserved (Assets)"

[[mods]]
  modId       = "twigs"
  version     = "2.0.1+1.19"
  displayName = "Twigs"
  logoFile    = "icon.png"
  description = "A Minecraft mod all about building, adding new and interesting materials, as well as new renditions of current vanilla blocks."

[[dependencies.twigs]]
  modId="forge"
  mandatory=true
  versionRange="[41,)"
  ordering="NONE"
  side="BOTH"
[[dependencies.twigs]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.19,)"
  ordering="NONE"
  side="BOTH"
